include_recipe './cookbooks/homebrew.rb'
include_recipe './cookbooks/packages.rb'
include_recipe './cookbooks/casks.rb'
include_recipe './cookbooks/store_apps.rb'
include_recipe './cookbooks/dotfiles.rb'
include_recipe './cookbooks/preferences.rb'
